const customizeConstants = {
	HIDE_MENU_DRAWER: 'HIDE_MENU_DRAWER',
	HIDE_MOBILE_DASHBOARD_MENU_DRAWER: 'HIDE_MOBILE_DASHBOARD_MENU_DRAWER',
	HIDE_MOBILE_DASHBOARD_SETTING_DRAWER: 'HIDE_MOBILE_DASHBOARD_SETTING_DRAWER',
	HIDE_MOBILE_DASHBOARD_NOTIFY_DRAWER: 'HIDE_MOBILE_DASHBOARD_NOTIFY_DRAWER',
	HIDE_USER_ACCOUNT_DROP_DOWN: 'HIDE_USER_ACCOUNT_DROP_DOWN'
};

export default customizeConstants;
