const userConstants = {
	USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

	USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

	USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
	USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
	USER_LOGOUT_FAIL: 'USER_LOGOUT_FAIL',

	USER_LOGIN_CHECK_REQUEST: 'USER_LOGIN_CHECK_REQUEST',
	USER_LOGIN_CHECK_SUCCESS: 'USER_LOGIN_CHECK_SUCCESS',
	USER_LOGIN_CHECK_FAIL: 'USER_LOGIN_CHECK_FAIL'
};

export default userConstants;
